version: "3.7"
services:
  supervisord:
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - ./source:/var/www/html
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - 8080:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always
